### ISSUE TITLE
Incomplete Slack channels list

### ISSUE THREAD

**Issue by jingo64** [questions-answers/community#18]
Hi!

We've just started using your integration, its pretty neat! One challenge is, we created a new Slack channel specifically with the goal in mind of using it for a Slack integration, however it doesn't show in the dropdown.

The dropdown list of channels just seems to be ordered based on channel creation date, and is limited to something like 50. Our current workspace has 100s of channels in, so this isn't very practical. Is it possible to make this searchable? Or that we can just type in the name of a channel which isn't in the dropdown, and just try to connect to it anyway?

Thanks!

**Comment by Lucasus** [comment]
Hello @jingo64, 

Indeed, there's a default limit of channels returned from Slack which was causing problems. 

I've just applied a fix for it. Channel selection list is now searchable - when you start typing channel's name in channel selection input, it should appear on a filtered drop down list of channels below so you'll be able to select it. Could you let me know if this fix solved your issue or if there are still some problems (e.g. performance related)?

Thanks for reporting this issue and sorry for your inconvenience!

**Comment by jingo64** [comment]
@Lucasus super speedy response, thank you so much! Works perfectly, sorry for my late response, I hadn't expected to hear anything so quickly 😄

**Comment by Lucasus** [comment]
@jingo64 glad I could help :) It's very important for me to keep app's experience as good as possible, so I'm trying to react fast, especially when problem seems to be easy to solve
