### ISSUE TITLE
Number of Licensed Users

### ISSUE THREAD

**Issue by enerAshwin** [questions-answers/community#23]
In the Pricing when you say 11-100 users are you referring to Confluence Users? We have confluence spaces accessible by Customers too. And, they won't be having privileges for viewing or asking questions. Will they still be billed? 

Would appreciate if you can respond back ASAP

**Comment by Lucasus** [comment]
Users in the Pricing refer to Confluence Users (users with Confluence account), so it's the same as for any other Confluence Cloud app. Just bear in mind that we don't have yet support for anonymous users so customers won't be able to access questions if they don't have active accounts in your instance
