### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by enerAshwin** [questions-answers/community#24]
Further to our evaluation of different plugins we had finally decided to proceed with your plugin. However, the notifications doesn't seem to be working. It does not send us notification when we create the Question neither does it do it when we Answer it.
Please have a look and let us know.

**Comment by Lucasus** [comment]
@enerAshwin I'm very happy that you've decided to use our application! When it comes to your problems with notifications, could you contact me by email? If you could send me a message at contact@questions-answers-community.com

**Comment by Lucasus** [comment]
Also just for you to know, we've found some issues when it comes to email delivery and we're working on fixing them

**Comment by Lucasus** [comment]
Confirmed with @enerAshwin that issue has been fixed
