### ISSUE TITLE
Integration with MS Teams does not work anymore 

### ISSUE THREAD

**Issue by Reiko3000** [questions-answers/community#29]
The new webhook generated by MS Teams has the following format:
https://companyName.webhook.office.com/webhookb2/bff9d20b-a968-4af5-991e-df725edbe6bf@245c3371-edb8-4214-a086-38801a1f4977/IncomingWebhook/f8d0ca87259d4b45a05428968421fcbd/524bbca6-aec1-4b9a-a2d0-694642c473de

The Q&A plugin expects the old format for the webhook url to connect to Teams, which is "https://outlook.office.com/webhook/...."
For already created webhooks, the old format will become deprecated by mid April 2021
If we want to create a new webhook in Teams, we cannot get\use the old format after Monday January 11, 2021 - thus integrate with your Q&A plugin

**Comment by Lucasus** [comment]
Hi @Reiko3000 I can confirm the bug, we're on it

**Comment by Lucasus** [comment]
@Reiko3000 We've deployed the bug fix. Could you confirm that setting up MS Teams webhooks works correctly now? Thanks for reporting this issue!

**Comment by Reiko3000** [comment]
@Lucasus I confirm the problem is fixed. Thank you for addressing this so quickly!

**Comment by Lucasus** [comment]
Glad I could help @Reiko3000!
